elfin:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 1000
    
    admittance_controller:
      type: arm_controllers/AdmittanceController
      joints:
        - elfin_joint1
        - elfin_joint2
        - elfin_joint3
        - elfin_joint4
        - elfin_joint5
        - elfin_joint6
        - ft_sensor_joint

      root_link: elfin_base_link
      tip_link: elfin_tool_ball
      
      joint1:
        tdc: {mbar: 0.02, r: 10.0, a: 50.0, w: 0.004}
      joint2: 
        tdc: {mbar: 0.02, r: 10.0, a: 50.0, w: 0.004}
      joint3: 
        tdc: {mbar: 0.01, r: 10.0, a: 50.0, w: 0.004}
      joint4: 
        tdc: {mbar: 0.004, r: 10.0, a: 50.0, w: 0.004}
      joint5: 
        tdc: {mbar: 0.003, r: 10.0, a: 50.0, w: 0.004}
      joint6: 
        tdc: {mbar: 0.001, r: 10.0, a: 50.0, w: 0.004}
      joint7:
        tdc: {mbar: 0.0, r: 0.0, a: 0.0, w: 0.0}

      aic: {fd: 20.0, m: 5.0, b: 300.0}

      # mode = 0 -> No Filter, Fd(fixed)
      # mode = 1 -> Filter, Fd(fixed)
      # mode = 2 -> Filter, Fd(sin)

      mode: 2

      gains:
        elfin_joint1: 
          pid: {p: 100.0, i: 0, d: 20.0}
        elfin_joint2: 
          pid: {p: 100.0, i: 0, d: 20.0}
        elfin_joint3: 
          pid: {p: 100.0, i: 0, d: 20.0}
        elfin_joint4: 
          pid: {p: 100.0, i: 0, d: 20.0}
        elfin_joint5: 
          pid: {p: 100.0, i: 0, d: 20.0}
        elfin_joint6: 
          pid: {p: 100.0, i: 0, d: 20.0}


      # root_link: world
      # tip_link: elfin_link6

      ctr_obj: 1  # ctr_obj = 1: Regulation 
                  # ctr_obj = 2: Tracking
                  
      ik_mode: 2 # open-loop inverse kinematics using jacobian
                 # closed-loop inverse Kinematics using jacobian

      clik_gain: {K_regulation: 6.0, K_tracking: 1.0}


